num = int(input('введите число ',))
bin_num = bin(num)
oct_num = oct(num)
hex_num = hex(num)
print(bin_num[2:],' - двоичная')
print(oct_num[2:],' -восмеричная')
print(hex_num[2:].upper(),'- шестнадцатеричная')
